### ISSUE TITLE
无法get带有下划线的文件

### ISSUE THREAD

**Issue by YushunXiang** [2ndelement/ssd8-network-work#1]
get带有下划线的文件失效，如在客户端 `get test_test` 操作失败。对于 `Exercise1-FTP/src/org/sec/ftp/command/GETCommand.java` 第23行的字符串替换操作 `replace` 导致下划线替换为空格。（可能是个人习惯问题，我还是很喜欢用下划线来区分文件名单词的QAQ）

**Comment by 2ndelement** [comment]
感谢测试！

为实现多个文件的传参和统一命令参数规范，采用了`.split(" ")`分割参数。

当时为了解决 带空格文件 的 传参问题，决定将下划线代替空格，但没有考虑下划线本身也很常用。

现在将采用

- 识别空格转义 `\<space>`
- 给单个文件参数加上引号 `"<filename with space>"`

以上方式来进行带空格的文件输入。
